[serviceweaver]
binary = "./emojis"

["emojis/ChatGPT"]
api_key = "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"

[single]
listeners.emojis = {address = "localhost:9000"}

[multi]
listeners.emojis = {address = "localhost:9000"}


